version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: water-assessment-dev
    env_file:
      - ./.env
    volumes:
      - ./data:/home/working/data:ro
      - ./:/home/working/
    working_dir: /home/working
    tty: true
    stdin_open: true
