version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: water-assessment-dev
    env_file:
      - ./.env
    volumes:
      - ./data:/home/working/data:ro

    # This part is used to enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
